# Generated by Django 5.1.6 on 2025-02-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('telefono_email', models.CharField(max_length=255)),
                ('metodo_entrega', models.CharField(choices=[('local', 'Retiro en el local'), ('cadete', 'Envío por cadete (+$3000, solo Carlos Paz)')], max_length=10)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de débito/crédito')], max_length=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
