# Generated by Django 5.1.6 on 2025-03-02 15:18

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(default='No especificado', max_length=50),
        ),
    ]
