# Generated by Django 5.1.6 on 2025-03-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_compra_cliente_nombre_compra_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente_nombre',
            field=models.CharField(default='anonimo', max_length=255),
            preserve_default=False,
        ),
    ]
