# Generated by Django 5.1.6 on 2025-03-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cliente_nombre',
            field=models.CharField(default='Anónimo', max_length=255),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
