# Generated by Django 5.1.6 on 2025-03-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_compra_cliente_nombre_alter_compra_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente_nombre',
        ),
        migrations.AddField(
            model_name='compra',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='cliente_nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='producto',
            field=models.CharField(max_length=100),
        ),
    ]
