# Generated by Django 5.1.6 on 2025-04-13 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_remove_pedido_cliente_nombre_compra_comprobante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='pedidos.categoria'),
        ),
    ]
