# Generated by Django 5.1.6 on 2025-04-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_categoria_categoria_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
