# Generated by Django 5.1.6 on 2025-04-12 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_categoria_nombre_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='productos.categoria'),
        ),
    ]
